{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "loan.secretName" . }}
  labels:
    {{- include "loan.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
    name: {{ .Values.externalSecret.secretStoreRef.name }}
  target:
    name: {{ include "loan.secretName" . }}
    creationPolicy: Owner
  data:
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: {{ include "loan.remoteKey" (list "externalSecret.remoteSecretName" .Values.externalSecret.remoteSecretName) }}
        property: password
    - secretKey: SERVICE_CLIENT_SECRET
      remoteRef:
        key: {{ include "loan.remoteKey" (list "externalSecret.serviceClientSecretName" .Values.externalSecret.serviceClientSecretName) }}
        property: client_secret
{{- end }}
