apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "loan.name" . }}
  labels:
    {{- include "loan.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable | int }}
  selector:
    matchLabels:
      {{- include "loan.selectorLabels" . | nindent 6 }}
